# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.models.vektis_agb_web_api_raadplegen_data_contracts_v2_zorgverlener_zorgverlener import VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener

class TestVektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener(unittest.TestCase):
    """VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener:
        """Test VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener`
        """
        model = VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener()
        if include_optional:
            return VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener(
                agb_code = '01234567',
                aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                einde = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                voorletters = '0',
                tussenvoegsel = '',
                achternaam = '0',
                geboortenaam_tussenvoegsel = '',
                geboortenaam = '',
                academische_titel = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/academische_titel.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.AcademischeTitel(
                    code = '0', 
                    omschrijving = '0', ),
                geslacht = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/geslacht.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Geslacht(
                    code = '0', 
                    omschrijving = '0', ),
                geboorte_datum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                kwalificaties = [
                    vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/v2/zorgpartij/zorgpartij_kwalificatie.Vektis.AGB.WebAPI.Raadplegen.DataContracts.v2.Zorgpartij.ZorgpartijKwalificatie(
                        aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        einde = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        code = '0123', 
                        omschrijving = '0', 
                        nictiz_code = '', 
                        patiententerm = '', )
                    ],
                erkenningen = [
                    vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/v2/zorgpartij/zorgpartij_erkenning.Vektis.AGB.WebAPI.Raadplegen.DataContracts.v2.Zorgpartij.ZorgpartijErkenning(
                        aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        einde = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        code = '012345', 
                        omschrijving = '0', 
                        registratie_nummer = '0', )
                    ],
                zorgsoort = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgsoort.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Zorgsoort(
                    code = '0', 
                    omschrijving = '0', )
            )
        else:
            return VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener(
                agb_code = '01234567',
                aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                voorletters = '0',
                achternaam = '0',
                geslacht = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/geslacht.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Geslacht(
                    code = '0', 
                    omschrijving = '0', ),
                geboorte_datum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                zorgsoort = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgsoort.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Zorgsoort(
                    code = '0', 
                    omschrijving = '0', ),
        )
        """

    def testVektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener(self):
        """Test VektisAGBWebAPIRaadplegenDataContractsV2ZorgverlenerZorgverlener"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
