# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.models.vektis_agb_web_api_raadplegen_data_contracts_v1_zorgpartij_zorgpartij_mutaties import VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties

class TestVektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties(unittest.TestCase):
    """VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties:
        """Test VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties`
        """
        model = VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties()
        if include_optional:
            return VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties(
                zorgpartijen = [
                    vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/v1/zorgpartij/zorgpartij_mutatie.Vektis.AGB.WebAPI.Raadplegen.DataContracts.v1.Zorgpartij.ZorgpartijMutatie(
                        agb_code = '01234567', 
                        zorgpartij_type = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgpartij_type.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.ZorgpartijType(
                            code = '0', 
                            omschrijving = '0', ), )
                    ]
            )
        else:
            return VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties(
        )
        """

    def testVektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties(self):
        """Test VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutaties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
