# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.models.vektis_agb_web_api_raadplegen_data_contracts_v1_zorgpartij_zorgpartij_mutatie import VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie

class TestVektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie(unittest.TestCase):
    """VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie:
        """Test VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie`
        """
        model = VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie()
        if include_optional:
            return VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie(
                agb_code = '01234567',
                zorgpartij_type = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgpartij_type.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.ZorgpartijType(
                    code = '0', 
                    omschrijving = '0', )
            )
        else:
            return VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie(
                agb_code = '01234567',
                zorgpartij_type = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgpartij_type.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.ZorgpartijType(
                    code = '0', 
                    omschrijving = '0', ),
        )
        """

    def testVektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie(self):
        """Test VektisAGBWebAPIRaadplegenDataContractsV1ZorgpartijZorgpartijMutatie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
