# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.api.referentiegegevens_api import ReferentiegegevensApi


class TestReferentiegegevensApi(unittest.TestCase):
    """ReferentiegegevensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferentiegegevensApi()

    def tearDown(self) -> None:
        pass

    def test_referentiegegevens_academische_titels(self) -> None:
        """Test case for referentiegegevens_academische_titels

        AGB010: Raadplegen van alle geldige academische titels
        """
        pass

    def test_referentiegegevens_adres_types(self) -> None:
        """Test case for referentiegegevens_adres_types

        AGB022: Raadplegen van alle adrestypes
        """
        pass

    def test_referentiegegevens_arbeids_relatie_rollen(self) -> None:
        """Test case for referentiegegevens_arbeids_relatie_rollen

        AGB012: Raadplegen van arbeidsrelatierollen voor een zorgverlener
        """
        pass

    def test_referentiegegevens_beheerders(self) -> None:
        """Test case for referentiegegevens_beheerders

        AGB011: Raadplegen van alle Beheerders/verleners agbcode
        """
        pass

    def test_referentiegegevens_bekend(self) -> None:
        """Test case for referentiegegevens_bekend

        Verifieren van een adres tegen AGB
        """
        pass

    def test_referentiegegevens_communicatie_gegeven_types(self) -> None:
        """Test case for referentiegegevens_communicatie_gegeven_types

        AGB021: Raadplegen van alle communicatiegegeventypes
        """
        pass

    def test_referentiegegevens_doelen(self) -> None:
        """Test case for referentiegegevens_doelen

        AGB028: Raadplegen van alle doelen
        """
        pass

    def test_referentiegegevens_erkenningen(self) -> None:
        """Test case for referentiegegevens_erkenningen

        AGB029: Raadplegen van alle geldige erkenningen
        """
        pass

    def test_referentiegegevens_geslachten(self) -> None:
        """Test case for referentiegegevens_geslachten

        COD046: Raadplegen van alle geldige geslachten
        """
        pass

    def test_referentiegegevens_kwalificaties(self) -> None:
        """Test case for referentiegegevens_kwalificaties

        AGB018: Raadplegen van alle geldige kwalificaties
        """
        pass

    def test_referentiegegevens_kwalificaties_onderneming_vestiging(self) -> None:
        """Test case for referentiegegevens_kwalificaties_onderneming_vestiging

        AGB018: Raadplegen van alle geldige kwalificaties voor ondernemingen en vestigingen
        """
        pass

    def test_referentiegegevens_kwalificaties_zorgverlener(self) -> None:
        """Test case for referentiegegevens_kwalificaties_zorgverlener

        AGB018: Raadplegen van alle geldige kwalificaties voor zorgverleners
        """
        pass

    def test_referentiegegevens_landen(self) -> None:
        """Test case for referentiegegevens_landen

        COD032-NEN: Raadplegen van alle landen
        """
        pass

    def test_referentiegegevens_provincies(self) -> None:
        """Test case for referentiegegevens_provincies

        AGB014: Raadplegen van alle provincies
        """
        pass

    def test_referentiegegevens_redenen_einde(self) -> None:
        """Test case for referentiegegevens_redenen_einde

        AGB009: Raadplegen van geldige redenen voor beeindigen lidmaatschap(erkenning)
        """
        pass

    def test_referentiegegevens_relatie_rollen(self) -> None:
        """Test case for referentiegegevens_relatie_rollen

        AGB012: Raadplegen van alle relatierollen
        """
        pass

    def test_referentiegegevens_relatie_types(self) -> None:
        """Test case for referentiegegevens_relatie_types

        AGB020: Raadplegen van alle relatietypes
        """
        pass

    def test_referentiegegevens_voorvoegsels(self) -> None:
        """Test case for referentiegegevens_voorvoegsels

        NAM040: Raadplegen van alle geldige voorvoegsels
        """
        pass

    def test_referentiegegevens_werkzaam_bij_rollen(self) -> None:
        """Test case for referentiegegevens_werkzaam_bij_rollen

        AGB012: Raadplegen van geldige werkzaambijrollen voor een zorgverlener
        """
        pass

    def test_referentiegegevens_zorgpartij_types(self) -> None:
        """Test case for referentiegegevens_zorgpartij_types

        AGB001: Raadplegen van alle zorgpartijtypes
        """
        pass

    def test_referentiegegevens_zorgsoorten_onderneming_vestiging(self) -> None:
        """Test case for referentiegegevens_zorgsoorten_onderneming_vestiging

        AGB016: Raadplegen van alle geldige zorgsoorten voor een onderneming en vestiging
        """
        pass

    def test_referentiegegevens_zorgsoorten_zorgverlener(self) -> None:
        """Test case for referentiegegevens_zorgsoorten_zorgverlener

        AGB015: Raadplegen van alle geldige zorgsoorten voor een zorgverlener
        """
        pass


if __name__ == '__main__':
    unittest.main()
