# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.models.vektis_agb_web_api_raadplegen_data_contracts_v2_zorgpartij_actieve_zorgpartijen import VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen

class TestVektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen(unittest.TestCase):
    """VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen:
        """Test VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen`
        """
        model = VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen()
        if include_optional:
            return VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen(
                paginanummer = 56,
                paginagrootte = 56,
                totaalpaginas = 56,
                totaalrecords = 56,
                data = [
                    vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/v2/zorgpartij/actieve_zorgpartij.Vektis.AGB.WebAPI.Raadplegen.DataContracts.v2.Zorgpartij.ActieveZorgpartij(
                        agb_code = '', 
                        aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        einde = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        zorgsoort = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgsoort.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Zorgsoort(
                            code = '0', 
                            omschrijving = '0', ), 
                        type = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/zorgpartij_type.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.ZorgpartijType(
                            code = '0', 
                            omschrijving = '0', ), )
                    ],
                succeeded = True,
                errors = [
                    ''
                    ],
                message = ''
            )
        else:
            return VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen(
        )
        """

    def testVektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen(self):
        """Test VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijActieveZorgpartijen"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
