# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.models.vektis_agb_web_api_raadplegen_data_contracts_v2_zorgpartij_communicatiegegeven import VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven

class TestVektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven(unittest.TestCase):
    """VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven:
        """Test VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven`
        """
        model = VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven()
        if include_optional:
            return VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven(
                aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                einde = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                doel = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/doel.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Doel(
                    code = '0', 
                    omschrijving = '0', ),
                gegeven = '0',
                type = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/communicatiegegeven_type.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.CommunicatiegegevenType(
                    code = '0', 
                    omschrijving = '0', )
            )
        else:
            return VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven(
                aanvang = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                doel = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/doel.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.Doel(
                    code = '0', 
                    omschrijving = '0', ),
                gegeven = '0',
                type = vektis_api.models.vektis/agb/web_api/raadplegen/data_contracts/referentiegegevens/communicatiegegeven_type.Vektis.AGB.WebAPI.Raadplegen.DataContracts.Referentiegegevens.CommunicatiegegevenType(
                    code = '0', 
                    omschrijving = '0', ),
        )
        """

    def testVektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven(self):
        """Test VektisAGBWebAPIRaadplegenDataContractsV2ZorgpartijCommunicatiegegeven"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
