# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vektis_api.api.onderneming_api import OndernemingApi


class TestOndernemingApi(unittest.TestCase):
    """OndernemingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OndernemingApi()

    def tearDown(self) -> None:
        pass

    def test_onderneming_basisinformatie(self) -> None:
        """Test case for onderneming_basisinformatie

        Raadplegen van basisinformatie van een onderneming
        """
        pass

    def test_onderneming_basisinformatie_0(self) -> None:
        """Test case for onderneming_basisinformatie_0

        Raadplegen van basisinformatie van een onderneming op peildatum
        """
        pass

    def test_onderneming_onderneming_organisatie_v2(self) -> None:
        """Test case for onderneming_onderneming_organisatie_v2

        Raadplegen vestigingen bij een onderneming
        """
        pass

    def test_onderneming_onderneming_organisatie_v2_0(self) -> None:
        """Test case for onderneming_onderneming_organisatie_v2_0

        Raadplegen vestigingen bij een onderneming op peildatum
        """
        pass

    def test_onderneming_onderneming_relaties_totaal_v2(self) -> None:
        """Test case for onderneming_onderneming_relaties_totaal_v2

        Raadplegen van alle relaties van een onderneming
        """
        pass

    def test_onderneming_onderneming_relaties_v2(self) -> None:
        """Test case for onderneming_onderneming_relaties_v2

        Raadplegen van huidige actieve relaties van een onderneming
        """
        pass

    def test_onderneming_onderneming_relaties_v2_0(self) -> None:
        """Test case for onderneming_onderneming_relaties_v2_0

        Raadplegen van actieve relaties van een onderneming op peildatum
        """
        pass

    def test_onderneming_zorgpartij_mutaties(self) -> None:
        """Test case for onderneming_zorgpartij_mutaties

        Raadplegen van ondernemingen met mutaties
        """
        pass

    def test_onderneming_zorgpartij_mutaties_0(self) -> None:
        """Test case for onderneming_zorgpartij_mutaties_0

        Raadplegen van ondernemingen met mutaties binnen het opgegeven zorgsoort.
        """
        pass


if __name__ == '__main__':
    unittest.main()
