# coding: utf-8

"""
    Vektis.AGB.WebAPI.Raadplegen (test-agb-api.vektis.nl/) v2

    De raadpleegdienst biedt de mogelijkheid voor diverse bevragingen op AGB. De informatie die beschikbaar is, kan gebruikt worden voor het aanvragen van AGB-codes met de aanvraagdienst.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from vektis_api.models.vektis_agb_web_api_raadplegen_data_contracts_v2_onderneming_adres import VektisAGBWebAPIRaadplegenDataContractsV2OndernemingAdres
from typing import Optional, Set
from typing_extensions import Self

class VektisAGBWebAPIRaadplegenDataContractsV2OndernemingVestigingOrganisatie(BaseModel):
    """
    
    """ # noqa: E501
    aanvang_agb_code: datetime = Field(description="DATUMAANVANG, dateTime, Datum vanaf wanneer een AGBCode geldig is", alias="AanvangAGBCode")
    einde_agb_code: Optional[datetime] = Field(default=None, description="DATUMEINDE, dateTime, Datum tot en met wanneer de AGBCode geldig is", alias="EindeAGBCode")
    aanvang_relatie: datetime = Field(description="DATUMAANVANG, dateTime, Datum tot en met wanneer een relatie geldig is", alias="AanvangRelatie")
    einde_relatie: Optional[datetime] = Field(default=None, description="DATUMEINDE, dateTime, Datum vanaf wanneer een relatie geldig is", alias="EindeRelatie")
    agb_code: Annotated[str, Field(min_length=8, strict=True, max_length=8)] = Field(description="CODE, length = 8 numeriek in een string, AGBCode", alias="AGBCode")
    bezoek_adres: VektisAGBWebAPIRaadplegenDataContractsV2OndernemingAdres = Field(alias="BezoekAdres")
    naam: Annotated[str, Field(min_length=1, strict=True, max_length=150)] = Field(description="HANDELSNAAM1, maxLength = 150, Eerste handelsnaam waaronder de vestiging bekend is bij het handelsregister", alias="Naam")
    __properties: ClassVar[List[str]] = ["AanvangAGBCode", "EindeAGBCode", "AanvangRelatie", "EindeRelatie", "AGBCode", "BezoekAdres", "Naam"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VektisAGBWebAPIRaadplegenDataContractsV2OndernemingVestigingOrganisatie from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bezoek_adres
        if self.bezoek_adres:
            _dict['BezoekAdres'] = self.bezoek_adres.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VektisAGBWebAPIRaadplegenDataContractsV2OndernemingVestigingOrganisatie from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AanvangAGBCode": obj.get("AanvangAGBCode"),
            "EindeAGBCode": obj.get("EindeAGBCode"),
            "AanvangRelatie": obj.get("AanvangRelatie"),
            "EindeRelatie": obj.get("EindeRelatie"),
            "AGBCode": obj.get("AGBCode"),
            "BezoekAdres": VektisAGBWebAPIRaadplegenDataContractsV2OndernemingAdres.from_dict(obj["BezoekAdres"]) if obj.get("BezoekAdres") is not None else None,
            "Naam": obj.get("Naam")
        })
        return _obj


